version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    
  build:
    commands:
      - pip install -r src/requirements.txt -t src
      - aws s3 cp state_machine.asl.json s3://tcc3bucket/state_machine.asl.json
      - aws s3 rm s3://tcc3bucket/last_evaluated_key.json
      - sam deploy --template-file template.yaml --region sa-east-1 --stack-name tcc3 --s3-prefix tcc3 --s3-bucket tcc3bucket --capabilities CAPABILITY_IAM

