AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Function:
    Runtime: python3.7

Resources:
  FilterTweetsTableFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tcc3-filter-tweets-table
      CodeUri: src
      Handler: lambdas/filter_tweets_table.lambda_handler
      Policies:
        - AmazonDynamoDBReadOnlyAccess
        - AmazonS3FullAccess

  InsertFilteredTweetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tcc3-insert-filtered-tweets
      CodeUri: src
      Handler: lambdas/insert_filtered_tweets.lambda_handler
      Policies:
        - AmazonSSMReadOnlyAccess
        - AmazonDynamoDBFullAccess