AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Function:
    Runtime: python3.7

Resources:
  FilterTweetsTableFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tcc3-filter-tweets-table
      CodeUri: src/lambdas/filter_tweets_table
      Handler: lambdas/filter_tweets_table.lambda_handler
      Layers:
        - !Ref TCC3LambdaLayer
      Policies:
        - AmazonDynamoDBReadOnlyAccess
        - AmazonS3FullAccess

  InsertFilteredTweetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tcc3-filter-tweets-table
      CodeUri: src/lambdas/insert_filtered_tweets
      Handler: lambdas/insert_filtered_tweets.lambda_handler
      Layers:
        - !Ref TCC3LambdaLayer
  
  TCC3LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: tcc3-lambda-layer
      CompatibleRuntimes:
        - python3.7
      ContentUri: src/core
      RetentionPolicy: Delete